- platform: group
  unique_id: back_door_shades
  name: Back Door Shades
  entities:
  - cover.back_door_shade_a
  - cover.back_door_shade_b

- platform: group
  unique_id: basement_shades
  name: Basement Shades
  entities:
  - cover.gym_shade
  - cover.lounge_shade
  - cover.theatre_shade

- platform: group
  unique_id: big_den_shade
  name: Big Den Shade
  entities:
  - cover.den_shade_a

- platform: group
  unique_id: big_living_room_shades
  name: Big Living Room Shades
  entities:
  - cover.living_room_shade_c
  - cover.living_room_shade_d

- platform: group
  unique_id: big_office_shade
  name: Big Office Shade
  entities:
  - cover.office_shade_a

- platform: group
  unique_id: den_shades
  name: Den Shades
  entities:
  - cover.den_shade_a
  - cover.den_shade_b

- platform: group
  unique_id: family_room_shades
  name: Family Room Shades
  entities:
  - cover.back_door_shades
  - cover.kitchen_shades
  - cover.living_room_shades

- platform: group
  unique_id: kitchen_shades
  name: Kitchen Shades
  entities:
  - cover.kitchen_shade_a
  - cover.kitchen_shade_b

- platform: group
  unique_id: little_den_shade
  name: Little Den Shade
  entities:
  - cover.den_shade_b

- platform: group
  unique_id: little_living_room_shades
  name: Little Living Room Shades
  entities:
  - cover.living_room_shade_a
  - cover.living_room_shade_b

- platform: group
  unique_id: little_office_shade
  name: Little Office Shade
  entities:
  - cover.office_shade_b

- platform: group
  unique_id: living_room_shades
  name: Living Room Shades
  entities:
  - cover.living_room_shade_a
  - cover.living_room_shade_b
  - cover.living_room_shade_c
  - cover.living_room_shade_d

- platform: group
  unique_id: master_bedroom_shades
  name: Master Bedroom Shades
  entities:
  - cover.master_bedroom_shade_a
  - cover.master_bedroom_shade_b

- platform: group
  unique_id: office_shades
  name: Office Shades
  entities:
  - cover.office_shade_a
  - cover.office_shade_b
