automation: !include_dir_merge_list automations
cover: !include covers.yaml
emulated_hue: !include hue.yaml
fan: !include fans.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
light: !include lights.yaml
media_player: !include media_player.yaml
script: !include_dir_merge_named scripts
switch: !include switches.yaml
template: !include_dir_merge_list templates
