- platform: group
  unique_id: basement_lights
  name: Basement Lights
  entities:
  - light.bar_lights
  - light.bar_counter_lights
  - light.bulkhead_lights
  - light.gym_lights
  - light.lounge_lights
  - light.tbd_lights
  - light.theatre_lights

- platform: group
  unique_id: bookshelf_lights
  name: Bookshelf Lights
  entities:
  - light.bookshelf_potlights
  - light.bookshelf_spotlights

- platform: group
  unique_id: bottom_floor_lights
  name: Bottom Floor Lights
  entities:
  - light.bar_lights
  - light.bar_counter_lights
  - light.basement_bathroom_lights
  - light.basement_closet_lights
  - light.bulkhead_lights
  - light.cold_storage_lights
  - light.downstairs_lights
  - light.gym_lights
  - light.lounge_lights
  - light.side_stairs_lights
  - light.storage_lights
  - light.tbd_lights
  - light.theatre_lights
  - light.utility_room_lights

- platform: group
  unique_id: den_lamps
  name: Den Lamps
  entities:
  - light.den_lamp_a
  - light.den_lamp_b
  - light.den_lamp_c

- platform: group
  unique_id: family_room_lights
  name: Family Room Lights
  entities:
  - light.dmz_lights
  - light.kitchen_ceiling_lights
  - light.living_room_lights

- platform: group
  unique_id: main_floor_lights
  name: Main Floor Lights
  entities:
  - light.backyard_lights
  - light.den_fan_lights
  - light.den_lamps
  - light.den_lights
  - light.dining_room_ceiling_lights
  - light.dining_room_chandelier
  - light.dmz_lights
  - light.foyer_lights
  - light.garage_lights
  - light.kitchen_ceiling_lights
  - light.kitchen_counter_lights
  - light.kitchen_island_lights
  - light.living_room_lights
  - light.mudroom_closet_lights
  - light.mudroom_lights
  - light.powder_room_lights

- platform: group
  unique_id: outside_lights
  name: Outside Lights
  entities:
  - light.porch_lights
  - light.side_door_lights
  - light.soffit_lights

- platform: group
  unique_id: second_floor_lights
  name: Second Floor Lights
  entities:
  - light.bookshelf_lights
  - light.guest_bedroom_lights
  - light.hallway_lights
  - light.laundry_room_lights
  - light.master_bedroom_closet_lights
  - light.master_bedroom_fan_lights
  - light.master_bedroom_lights
  - light.office_closet_lights
  - light.office_lights
  - light.spare_bedroom_closet_lights
  - light.spare_bedroom_lights
  - light.upstairs_lights
  - light.workbench_lights

- platform: group
  unique_id: workbench_lights
  name: Workbench Lights
  entities:
  - light.workbench_light_a
  - light.workbench_light_b
