- platform: template
  lights:
    christmas_lights:
      unique_id: christmas_lights
      friendly_name: Christmas Lights
      value_template: >
        {{ (states.light | selectattr("entity_id", "search", "^light\.christmas(?!_lights)") | rejectattr("attributes.entity_id", "defined") | selectattr("state", "equalto", "on") | list | count) +
           (states.switch | selectattr("entity_id", "search", "^switch\.christmas(?!_lights)") | rejectattr("attributes.entity_id", "defined") | selectattr("state", "equalto", "on") | list | count) > 0}}
      turn_on:
      - action: light.turn_on
        target:
          entity_id: &christmas_lights
            '{{ states.light | selectattr("entity_id", "search", "^light\.christmas(?!_lights)") | rejectattr("attributes.entity_id", "defined") | map(attribute="entity_id") | list }}'
      - action: switch.turn_on
        target:
          entity_id: &christmas_switches
            '{{ states.switch | selectattr("entity_id", "search", "^switch\.christmas(?!_lights)") | rejectattr("attributes.entity_id", "defined") | map(attribute="entity_id") | list }}'
      turn_off:
      - action: light.turn_off
        target:
          entity_id: *christmas_lights
      - action: switch.turn_off
        target:
          entity_id: *christmas_switches

- platform: template
  lights:
    seasonal_lights:
      unique_id: seasonal_lights
      friendly_name: Seasonal Lights
      value_template: >
        {{ (states.light | selectattr("entity_id", "search", "^light\.seasonal(?!_lights)") | rejectattr("attributes.entity_id", "defined") | selectattr("state", "equalto", "on") | list | count) +
           (states.switch | selectattr("entity_id", "search", "^switch\.seasonal(?!_lights)") | rejectattr("attributes.entity_id", "defined") | selectattr("state", "equalto", "on") | list | count) > 0}}
      turn_on:
      - action: light.turn_on
        target:
          entity_id: &seasonal_lights
            '{{ states.light | selectattr("entity_id", "search", "^light\.seasonal(?!_lights)") | rejectattr("attributes.entity_id", "defined") | map(attribute="entity_id") | list }}'
      - action: switch.turn_on
        target:
          entity_id: &seasonal_switches
            '{{ states.switch | selectattr("entity_id", "search", "^switch\.seasonal(?!_lights)") | rejectattr("attributes.entity_id", "defined") | map(attribute="entity_id") | list }}'
      turn_off:
      - action: light.turn_off
        target:
          entity_id: *seasonal_lights
      - action: switch.turn_off
        target:
          entity_id: *seasonal_switches
